---
- name: Install LLDP
  ansible.builtin.package:
    name:
      - lldpd
    state: present

- name: Start and Enable LLDP Daemon
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: lldpd.service
