---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
  roles:
    - role: thost96.proxmox
      ignore_errors: true
      vars:
        # Additional pre-task neccessary
        disable_subscription_popup: false
        disable_enterprise_repo: true
        enable_no_subscription_repo: true
        # Additional pre-task neccessary for influx and graphite / or file validation only
        system_upgrades: true
        # Not yet implemented
        system_kernel_upgrade: false
        # Not yet implemented
        system_kernel_clean: false
        # Not yet implemented
        tools_cockpit: false
        tools_lldp: true
