---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    # Subscription Popup
    - name: Create JS directory
      file:
        path: /usr/share/javascript/proxmox-widget-toolkit
        state: directory
      when: "disable_subscription_popup | bool"
    - name: Create JS File
      file:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        state: touch
        access_time: preserve
        modification_time: preserve
      when: "disable_subscription_popup | bool"
    # All APT Tasks
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
    # InfluxDB / Graphite Metrics
    - name: Create proxmox config directory
      file:
        path: /etc/pve
        state: directory
      when: metrics_influx | bool or metrics_graphite | bool
    # Zamba LXC Toolbox
    - name: Create root home dir
      file:
        path: /home/root
        state: directory
      when: tools_zamba_lxc_toolbox == true
  roles:
    - role: thost96.proxmox
      ignore_errors: true
      vars:
        disable_subscription_popup: true
        disable_enterprise_repo: true
        enable_no_subscription_repo: true
        system_upgrades: true
        system_kernel_clean: true
        tools_lldp: true
        tools_cockpit: true
        tools_zamba_lxc_toolbox: true
        # Additional pre-task neccessary for influx and graphite / or file validation only
        metrics_influx: false
        metrics_influx_server: "influx"
        metrics_influx_port: 8089
        metrics_graphite: false
        metrics_graphite_server: "graphite"
        metrics_graphite_port: 2003
  post_tasks:
    # Tools - Cockpit
    - name: Validate Cockpit version
      command: cockpit-bridge --version
      when: tools_cockpit == true
    - name: Check Cockpit ZFS Plugin dir
      command: ls -la /usr/share/cockpit/zfs/
      when: tools_cockpit == true
