---
name: Molecule Lint and Test

'on':
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          path: "${{ github.repository }}"

      - name: Molecule Action
        uses: robertdebock/molecule-action@6.0.0
        with:
          command: lint
