---
name: Molecule Test

'on':
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          path: "${{ github.repository }}"

      - name: Molecule Action
        uses: robertdebock/molecule-action@6.0.1
