---
name: Release

'on':
  push:
    tags:
      - '*'

env:
  GALAXY_USERNAME: thost96

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v1
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
